// fauna:bake — write client/shared/fauna-models.js from content/fauna_models/*.json.
//
//   npm run fauna:bake
//
// The sibling of vehicles:bake, for the animals. A fauna row is plain numbers and colours, so this
// bake resolves nothing and only moves them: it reads the directory, checks each file against the
// schema, refuses two files claiming one row, and writes the module fauna3d.js imports.
//
// WHY A BAKE AND NOT A RUNTIME READ, same answer as the vehicles and the buildings: fauna3d.js runs
// in a browser, there is no build step, and a mesh is built on the hot path. A module of literals
// costs nothing at runtime and cannot fail halfway.
//
// ⚠ Re-run after editing any file under content/fauna_models/. `npm run shapes:smoke` fails if you
// forget — it re-bakes in memory and diffs against the committed file.
import { writeFileSync, readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateFaunaRow, FAUNA_IDS, FAUNA_KINDS, faunaFileName } from '../../client/shared/fauna-model-schema.js';

const ROOT = new URL('../../', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const SRC = join(ROOT, 'content', 'fauna_models');
const OUT = join(ROOT, 'client', 'shared', 'fauna-models.js');

export function readFaunaFiles(dir = SRC) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((f) => f.endsWith('.json')).sort()
    .map((f) => ({ file: f, doc: JSON.parse(readFileSync(join(dir, f), 'utf8')) }));
}

export function bakeFauna(files = readFaunaFiles()) {
  const rows = {}, errors = [], warnings = [];
  for (const kind of FAUNA_KINDS) rows[kind] = {};
  for (const { file, doc } of files) {
    const v = validateFaunaRow(doc, file);
    errors.push(...v.errors); warnings.push(...v.warnings);
    if (v.errors.length) continue;
    // The name is derived from the row, so a file cannot be authored under one id and read as
    // another — the trap that a directory keyed on filename has and a table does not.
    const want = faunaFileName(doc.kind, doc.id);
    if (file !== want) { errors.push(file + ': a ' + doc.kind + ' row for ' + doc.id + ' must be called ' + want); continue; }
    if (rows[doc.kind][doc.id]) { errors.push(file + ': ' + doc.kind + '/' + doc.id + ' is authored twice'); continue; }
    rows[doc.kind][doc.id] = doc.params;
  }
  // A missing row is an animal the renderer has no shape for at all — there is no FW_DEFAULT here
  // to fall back on — so it is an error and not a warning. The file is the whole of what it is.
  for (const kind of FAUNA_KINDS) {
    for (const id of FAUNA_IDS[kind]) {
      if (!rows[kind][id]) errors.push('no file for ' + kind + '/' + id + ' (' + faunaFileName(kind, id) + ')');
    }
  }
  return { rows, errors, warnings };
}

// Keys in authored order per row is not available (JSON objects are read sorted by the writer), so
// this prints them sorted — the same order canonicalJson puts them in the file, which keeps the
// bake diff and the content diff readable side by side.
function lit(v) {
  if (v === null || typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return '[' + v.map((x) => lit(x)).join(', ') + ']';
  const inner = Object.keys(v).sort().map((k) => JSON.stringify(k) + ': ' + lit(v[k]));
  return '{ ' + inner.join(', ') + ' }';
}

export function renderModule({ rows }) {
  const table = (kind) => Object.keys(rows[kind]).sort()
    .map((id) => '  ' + JSON.stringify(id) + ': ' + lit(rows[kind][id]) + ',').join('\n');
  return [
    '// GENERATED by scripts/shapes/bake-fauna.mjs — never edit by hand.',
    '//',
    '// One row per authored animal, read straight out of content/fauna_models/*.json. These are the',
    '// numbers fauna3d.js builds a mesh from; nothing here is geometry and nothing here is motion —',
    '// a row says what an animal IS, and windshield.js says what it does.',
    '//',
    '// Re-run `npm run fauna:bake` after editing any of those files. `npm run shapes:smoke` fails on',
    '// a stale bake rather than letting the module and the content disagree.',
    'export const BIRD_ROWS = {',
    table('bird'),
    '};',
    '',
  ].join('\n');
}

export function bakeToString(files) {
  const res = bakeFauna(files);
  return { ...res, text: res.errors.length ? null : renderModule(res) };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { errors, warnings, text } = bakeToString();
  for (const w of warnings) console.warn('warn: ' + w);
  if (errors.length) { for (const e of errors) console.error('error: ' + e); process.exit(1); }
  writeFileSync(OUT, text);
  console.log('fauna:bake → client/shared/fauna-models.js');
}
