// shapes:bake — write client/shared/building-shapes.js from the live flight-sim renderer.
//
//   npm run shapes:bake
//
// Why a baked file exists at all. The cold open (client/game/js/panels/intro-cinematic.js) draws
// the real Coldwater skyline as a wireframe on a player's FIRST LOGIN, and it must not import
// windshield.js to do it — that's ~8500 lines of flight renderer pulled in before the player has
// seen a word of prose. So the shapes are captured here, once, and shipped as a small data module
// next to skyline-scale.js, which is already the shared SSOT for how tall and wide a building is.
//
// Why it is safe to trust. The shapes are not transcribed by hand — they come out of the shipping
// renderer by running its own model arms with the mass primitives recording instead of drawing (see
// the SHAPE_SINK block in windshield.js). Re-running this script after editing a building model is
// the only maintenance step, and `npm run shapes:smoke` fails if you forget: it re-captures and
// compares against the committed file, so a stale bake is a red test rather than a silent drift.
//
// Each segment is a WIREFRAME BOX in the affine [a·fh + b·h + c] form — a multiple of the footprint
// half-width, plus a multiple of the storey-stack height, plus an absolute. The cold open's storeys
// are far taller than the sim's, and keeping the two bases separate is exactly what lets one bake
// serve a renderer and a cinematic that disagree about scale.
import { writeFileSync } from 'node:fs';
import { loadWindshield } from './dom-stub.mjs';

const OUT = new URL('../../client/shared/building-shapes.js', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
// The N most defining pieces, in rank order, with the TALLEST always included (a spire has almost
// no bulk but is most of a skyline). The cold open draws fewer than this on distant buildings — it
// strokes cages, and every edge is its own path — so this is a ceiling, not a per-frame cost.
// Was 5, which is a silhouette; 9 is a BUILDING. Five pieces buys the mass, the main setback and
// the spire, and everything a tower is actually recognised by — the second setback, the podium, the
// portico, the rooftop plant — fell off the end, so most of the city arrived as a slab with a stick
// on it. The cold open picks how many of these it strokes by distance, so the extra pieces cost
// nothing on a far building and are the whole difference on a near one.
const MAX_SEGS = 9;
const R = 5;          // decimals kept — a wireframe does not need micrometres

export function bakeShapes(ws) {
  const out = {};
  for (const { key, m } of ws.shapeModelRegistry()) {
    const segs = ws.shapeWireList(m, MAX_SEGS);
    if (!segs.length) continue;
    const round = (p) => p.map((v) => +v.toFixed(R));
    out[key] = segs.map((s) => {
      const rec = { cx: round(s.cx), cy: round(s.cy), hx: round(s.hx), hy: round(s.hy), z0: round(s.z0), z1: round(s.z1) };
      if (s.yaw) rec.yaw = +s.yaw.toFixed(4);
      if (s.front) rec.front = 1;
      // The real contour, where a piece has one. Absent means "a box", which is 90% of them.
      if (s.kind === 'drum') { rec.kind = 'drum'; rec.rb = round(s.rb); rec.rt = round(s.rt); rec.n = s.n; }
      else if (s.kind) rec.kind = s.kind;
      // The tallest piece — a spire, a crown, a water tower. Flagged because it has almost no bulk
      // and so sorts LAST, which means any consumer trimming the list by rank would drop exactly the
      // thing that gives a skyline its shape.
      if (s.tall) rec.tall = 1;
      return rec;
    });
  }
  return out;
}

export function renderModule(shapes) {
  const keys = Object.keys(shapes).sort();
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(shapes[k])},`).join('\n');
  return `// GENERATED by scripts/shapes/bake.mjs — do not edit by hand.
//
// The real shape of every Coldwater building, captured out of the flight-sim renderer
// (client/game/js/panels/windshield.js) so that things which are NOT the flight sim can know what a
// building looks like without importing it. The cold open is the reason it exists; collision and the
// ground shadow read the same geometry live, from the renderer itself.
//
// A segment is one wireframe piece: { cx, cy, hx, hy, z0, z1, yaw?, front?, kind? }, where cx…z1 are
// always its bounding box. \`kind\` is absent for a plain box; "drum" adds { rb, rt, n } (a faceted,
// possibly tapered cylinder) and "arch" marks a barrel roof. A consumer may draw the real contour or
// just the box — the box is always there. Every number is an
// affine triple [a, b, c] meaning \`a * footprintHalfWidth + b * storeyStackHeight + c\` — so a
// consumer picks its own scale, which is what lets the cold open use storeys six times taller than
// the sim's without the shapes drifting. \`front\` marks mass on the entrance face (a door or a
// loading bay). Segments are ordered most-defining first.
//
// Regenerate with \`npm run shapes:bake\`; \`npm run shapes:smoke\` fails if this file is stale.
export const BUILDING_SHAPES = {
${body}
};

// Same resolution order the renderer uses (windshield.js modelFor): a building's own named model
// first, then its building_type default. Keep these in step — a name that stops matching silently
// falls back to the type shape, which looks like nothing at all going wrong.
export const bldgSlug = (name) => (name || '').toLowerCase().replace(/[^a-z0-9]+/g, '');
export function shapeFor(name, buildingType) {
  return BUILDING_SHAPES['named:' + bldgSlug(name)] || BUILDING_SHAPES['type:' + buildingType] || null;
}
// Evaluate one affine triple at a chosen footprint/height scale.
export const shapeVal = (p, fh, h) => p[0] * fh + p[1] * h + p[2];
`;
}

async function main() {
  const ws = await loadWindshield();
  const shapes = bakeShapes(ws);
  const n = Object.keys(shapes).length;
  const segs = Object.values(shapes).reduce((a, s) => a + s.length, 0);
  const text = renderModule(shapes);
  writeFileSync(OUT, text, 'utf8');
  console.log(`✓ shapes:bake — ${n} models, ${segs} segments → client/shared/building-shapes.js (${(text.length / 1024).toFixed(1)} kB)`);
}

import { fileURLToPath } from 'node:url';
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
