// GENERATED by scripts/client/bake-lazy-view.mjs — do not edit by hand.
//
// A lazy facade over ./aircraft3d.js. Same export names, so an importing panel changes one
// line; the module itself is fetched on the first `loadAircraft3d()`, which every path that
// opens an immersive view awaits before it draws anything. See the generator for why.

let _m = null;
let _pending = null;

// Value exports, filled on load. These are ESM LIVE BINDINGS: an importer that reads one
// after `loadAircraft3d()` has resolved sees the real value, because an import binds rather
// than copies. Read one before that and it is undefined, which is why the loader is awaited
// at the door rather than at the first use.
export let CP_TH, CP_TW, CUB_GROUND_PITCH, JAZZ_ROLE, MODEL_NEAR_Z, MODEL_SCALE, OCCLUDE_ROLE, PROP_STATIONS, VIPER_GROUND_PITCH, VIPER_SCALE, truckLivery;

export function isLoaded() { return !!_m; }

export function loadAircraft3d() {
  if (_m) return Promise.resolve(_m);
  if (_pending) return _pending;
  _pending = (async () => {
    const m = await import('./aircraft3d.js');
    CP_TH = m.CP_TH;
    CP_TW = m.CP_TW;
    CUB_GROUND_PITCH = m.CUB_GROUND_PITCH;
    JAZZ_ROLE = m.JAZZ_ROLE;
    MODEL_NEAR_Z = m.MODEL_NEAR_Z;
    MODEL_SCALE = m.MODEL_SCALE;
    OCCLUDE_ROLE = m.OCCLUDE_ROLE;
    PROP_STATIONS = m.PROP_STATIONS;
    VIPER_GROUND_PITCH = m.VIPER_GROUND_PITCH;
    VIPER_SCALE = m.VIPER_SCALE;
    truckLivery = m.truckLivery;
    _m = m;
    return m;
  })();
  return _pending;
}

// ⚠ A WRAPPER CALLED BEFORE THE LOAD NAMES ITSELF. The one thing this refactor can get
// wrong is a path that uses a symbol without awaiting the loader, and `_m is null` is a
// TypeError from a generated file that points at nothing.
function _cold(name) {
  throw new Error("aircraft3d-lazy.js: " + name + "() was called before loadAircraft3d() resolved — await it on the path that opens this view.");
}

export function _resetTruckOrder(...a) { return (_m || _cold('_resetTruckOrder'))._resetTruckOrder(...a); }
export function aircraftFaces(...a) { return (_m || _cold('aircraftFaces')).aircraftFaces(...a); }
export function canopyTex(...a) { return (_m || _cold('canopyTex')).canopyTex(...a); }
export function cessnaSection(...a) { return (_m || _cold('cessnaSection')).cessnaSection(...a); }
export function clearVehicleFacesCache(...a) { return (_m || _cold('clearVehicleFacesCache')).clearVehicleFacesCache(...a); }
export function clearVehicleParams(...a) { return (_m || _cold('clearVehicleParams')).clearVehicleParams(...a); }
export function cubSection(...a) { return (_m || _cold('cubSection')).cubSection(...a); }
export function deflectSurface(...a) { return (_m || _cold('deflectSurface')).deflectSurface(...a); }
export function depthPassBuild(...a) { return (_m || _cold('depthPassBuild')).depthPassBuild(...a); }
export function depthPassCommit(...a) { return (_m || _cold('depthPassCommit')).depthPassCommit(...a); }
export function depthPassCount(...a) { return (_m || _cold('depthPassCount')).depthPassCount(...a); }
export function drawCanopyGlass(...a) { return (_m || _cold('drawCanopyGlass')).drawCanopyGlass(...a); }
export function drawCockpitProp(...a) { return (_m || _cold('drawCockpitProp')).drawCockpitProp(...a); }
export function drawHangarFloorBay(...a) { return (_m || _cold('drawHangarFloorBay')).drawHangarFloorBay(...a); }
export function drawHangarScene(...a) { return (_m || _cold('drawHangarScene')).drawHangarScene(...a); }
export function drawNoseArt(...a) { return (_m || _cold('drawNoseArt')).drawNoseArt(...a); }
export function drawRotorFX(...a) { return (_m || _cold('drawRotorFX')).drawRotorFX(...a); }
export function drawTruckDoorArt(...a) { return (_m || _cold('drawTruckDoorArt')).drawTruckDoorArt(...a); }
export function drawTurntable(...a) { return (_m || _cold('drawTurntable')).drawTurntable(...a); }
export function faceBaseRgb(...a) { return (_m || _cold('faceBaseRgb')).faceBaseRgb(...a); }
export function glassSheen(...a) { return (_m || _cold('glassSheen')).glassSheen(...a); }
export function groundPitchFor(...a) { return (_m || _cold('groundPitchFor')).groundPitchFor(...a); }
export function hex2rgb(...a) { return (_m || _cold('hex2rgb')).hex2rgb(...a); }
export function hingeVisorFace(...a) { return (_m || _cold('hingeVisorFace')).hingeVisorFace(...a); }
export function jazzTex(...a) { return (_m || _cold('jazzTex')).jazzTex(...a); }
export function jazzUV(...a) { return (_m || _cold('jazzUV')).jazzUV(...a); }
export function liveryPalette(...a) { return (_m || _cold('liveryPalette')).liveryPalette(...a); }
export function overlayJazz(...a) { return (_m || _cold('overlayJazz')).overlayJazz(...a); }
export function pickSceneHit(...a) { return (_m || _cold('pickSceneHit')).pickSceneHit(...a); }
export function setVehicleParams(...a) { return (_m || _cold('setVehicleParams')).setVehicleParams(...a); }
export function shadeRgb(...a) { return (_m || _cold('shadeRgb')).shadeRgb(...a); }
export function slideEase(...a) { return (_m || _cold('slideEase')).slideEase(...a); }
export function sortTruckFaces(...a) { return (_m || _cold('sortTruckFaces')).sortTruckFaces(...a); }
export function truckMeta(...a) { return (_m || _cold('truckMeta')).truckMeta(...a); }
export function vehicleLamps(...a) { return (_m || _cold('vehicleLamps')).vehicleLamps(...a); }
export function vehicleParamBase(...a) { return (_m || _cold('vehicleParamBase')).vehicleParamBase(...a); }
export function vehicleParamIds(...a) { return (_m || _cold('vehicleParamIds')).vehicleParamIds(...a); }
export function viperXf(...a) { return (_m || _cold('viperXf')).viperXf(...a); }
export function visorHidden(...a) { return (_m || _cold('visorHidden')).visorHidden(...a); }
export function visorSpecFor(...a) { return (_m || _cold('visorSpecFor')).visorSpecFor(...a); }
export function wingtipStation(...a) { return (_m || _cold('wingtipStation')).wingtipStation(...a); }

