// GENERATED by scripts/client/bake-lazy-view.mjs — do not edit by hand.
//
// A lazy facade over ./windshield.js. Same export names, so an importing panel changes one
// line; the module itself is fetched on the first `loadWindshield()`, which every path that
// opens an immersive view awaits before it draws anything. See the generator for why.

let _m = null;
let _pending = null;

// Value exports, filled on load. These are ESM LIVE BINDINGS: an importer that reads one
// after `loadWindshield()` has resolved sees the real value, because an import binds rather
// than copies. Read one before that and it is undefined, which is why the loader is awaited
// at the door rather than at the first use.
export let ADORN_CHEAP, ADORN_NEAR, ADORN_RICH, AUTHORED_ADORN_KINDS, AUTHORED_DETAIL_KINDS, BERTH_LIFTS, BERTH_SETDOWN, BERTH_SLOTS, BUILDING_FOOT, CAB_TRIM, CLIMBOUT_LAT_IN, CLIMBOUT_LAT_OUT, CLIMBOUT_MAX_F, CONTACT_NEAR_F, CURTAIN_H, CURTAIN_HALF_W, DETAIL_PX, FLASH_AREA, FLASH_BANK, FLASH_FLOOR, FT_PER_FLOOR, HUNT_REACH, LEGACY_MODELS, MAT_ORDER, MODEL_MAX_EXTENT, NO_TILE_FIT, RENDER_TUNE, ROAD_RIG_MUL, ROOF_CATCH_CEIL_Z, ROOF_CATCH_R, SIGN_FONT, SIGN_PICTO, SIGN_TRACK, TILE_REACH, TRUCK_STEP_Z, TRUCK_VARIANTS, VEHICLE_CLASSES, VEHICLE_PARAM_TABLE, VISIBLE_FAR_F, VISIBLE_NEAR_F, WIRE_RING_S, _bayCutaway, _resetTruckOrder, clearVehicleParams, setVehicleParams, sortTruckFaces, vehicleParamBase, vehicleParamIds;

export function isLoaded() { return !!_m; }

export function loadWindshield() {
  if (_m) return Promise.resolve(_m);
  if (_pending) return _pending;
  _pending = (async () => {
    const m = await import('./windshield.js');
    ADORN_CHEAP = m.ADORN_CHEAP;
    ADORN_NEAR = m.ADORN_NEAR;
    ADORN_RICH = m.ADORN_RICH;
    AUTHORED_ADORN_KINDS = m.AUTHORED_ADORN_KINDS;
    AUTHORED_DETAIL_KINDS = m.AUTHORED_DETAIL_KINDS;
    BERTH_LIFTS = m.BERTH_LIFTS;
    BERTH_SETDOWN = m.BERTH_SETDOWN;
    BERTH_SLOTS = m.BERTH_SLOTS;
    BUILDING_FOOT = m.BUILDING_FOOT;
    CAB_TRIM = m.CAB_TRIM;
    CLIMBOUT_LAT_IN = m.CLIMBOUT_LAT_IN;
    CLIMBOUT_LAT_OUT = m.CLIMBOUT_LAT_OUT;
    CLIMBOUT_MAX_F = m.CLIMBOUT_MAX_F;
    CONTACT_NEAR_F = m.CONTACT_NEAR_F;
    CURTAIN_H = m.CURTAIN_H;
    CURTAIN_HALF_W = m.CURTAIN_HALF_W;
    DETAIL_PX = m.DETAIL_PX;
    FLASH_AREA = m.FLASH_AREA;
    FLASH_BANK = m.FLASH_BANK;
    FLASH_FLOOR = m.FLASH_FLOOR;
    FT_PER_FLOOR = m.FT_PER_FLOOR;
    HUNT_REACH = m.HUNT_REACH;
    LEGACY_MODELS = m.LEGACY_MODELS;
    MAT_ORDER = m.MAT_ORDER;
    MODEL_MAX_EXTENT = m.MODEL_MAX_EXTENT;
    NO_TILE_FIT = m.NO_TILE_FIT;
    RENDER_TUNE = m.RENDER_TUNE;
    ROAD_RIG_MUL = m.ROAD_RIG_MUL;
    ROOF_CATCH_CEIL_Z = m.ROOF_CATCH_CEIL_Z;
    ROOF_CATCH_R = m.ROOF_CATCH_R;
    SIGN_FONT = m.SIGN_FONT;
    SIGN_PICTO = m.SIGN_PICTO;
    SIGN_TRACK = m.SIGN_TRACK;
    TILE_REACH = m.TILE_REACH;
    TRUCK_STEP_Z = m.TRUCK_STEP_Z;
    TRUCK_VARIANTS = m.TRUCK_VARIANTS;
    VEHICLE_CLASSES = m.VEHICLE_CLASSES;
    VEHICLE_PARAM_TABLE = m.VEHICLE_PARAM_TABLE;
    VISIBLE_FAR_F = m.VISIBLE_FAR_F;
    VISIBLE_NEAR_F = m.VISIBLE_NEAR_F;
    WIRE_RING_S = m.WIRE_RING_S;
    _bayCutaway = m._bayCutaway;
    _resetTruckOrder = m._resetTruckOrder;
    clearVehicleParams = m.clearVehicleParams;
    setVehicleParams = m.setVehicleParams;
    sortTruckFaces = m.sortTruckFaces;
    vehicleParamBase = m.vehicleParamBase;
    vehicleParamIds = m.vehicleParamIds;
    _m = m;
  try { (await import('./gl/install.js')).installGL?.(); } catch (e) { console.error('[windshield-lazy] GL install failed, staying on the 2-D renderer:', e?.message); }
    return m;
  })();
  return _pending;
}

// ⚠ A WRAPPER CALLED BEFORE THE LOAD NAMES ITSELF. The one thing this refactor can get
// wrong is a path that uses a symbol without awaiting the loader, and `_m is null` is a
// TypeError from a generated file that points at nothing.
function _cold(name) {
  throw new Error("windshield-lazy.js: " + name + "() was called before loadWindshield() resolved — await it on the path that opens this view.");
}

export function _blockSpan(...a) { return (_m || _cold('_blockSpan'))._blockSpan(...a); }
export function _elbowSweep(...a) { return (_m || _cold('_elbowSweep'))._elbowSweep(...a); }
export function accentOf(...a) { return (_m || _cold('accentOf')).accentOf(...a); }
export function altForRoofZ(...a) { return (_m || _cold('altForRoofZ')).altForRoofZ(...a); }
export function altRestingOnZ(...a) { return (_m || _cold('altRestingOnZ')).altRestingOnZ(...a); }
export function armSignsItself(...a) { return (_m || _cold('armSignsItself')).armSignsItself(...a); }
export function authoredAdornSmoke(...a) { return (_m || _cold('authoredAdornSmoke')).authoredAdornSmoke(...a); }
export function authoredDetailSmoke(...a) { return (_m || _cold('authoredDetailSmoke')).authoredDetailSmoke(...a); }
export function bayDoorOpen(...a) { return (_m || _cold('bayDoorOpen')).bayDoorOpen(...a); }
export function bayMassSmoke(...a) { return (_m || _cold('bayMassSmoke')).bayMassSmoke(...a); }
export function bayOccluderSmoke(...a) { return (_m || _cold('bayOccluderSmoke')).bayOccluderSmoke(...a); }
export function berthBoxColour(...a) { return (_m || _cold('berthBoxColour')).berthBoxColour(...a); }
export function berthPhase(...a) { return (_m || _cold('berthPhase')).berthPhase(...a); }
export function berthRow(...a) { return (_m || _cold('berthRow')).berthRow(...a); }
export function boatBreakup(...a) { return (_m || _cold('boatBreakup')).boatBreakup(...a); }
export function buildLedges(...a) { return (_m || _cold('buildLedges')).buildLedges(...a); }
export function buildingHeightZ(...a) { return (_m || _cold('buildingHeightZ')).buildingHeightZ(...a); }
export function buildingRoofFt(...a) { return (_m || _cold('buildingRoofFt')).buildingRoofFt(...a); }
export function buildingRoofFtAt(...a) { return (_m || _cold('buildingRoofFtAt')).buildingRoofFtAt(...a); }
export function buildingScaleFor(...a) { return (_m || _cold('buildingScaleFor')).buildingScaleFor(...a); }
export function cabControlRects(...a) { return (_m || _cold('cabControlRects')).cabControlRects(...a); }
export function cabDashCanvas(...a) { return (_m || _cold('cabDashCanvas')).cabDashCanvas(...a); }
export function cabGpsRect(...a) { return (_m || _cold('cabGpsRect')).cabGpsRect(...a); }
export function cabTrim(...a) { return (_m || _cold('cabTrim')).cabTrim(...a); }
export function cabWheelGeom(...a) { return (_m || _cold('cabWheelGeom')).cabWheelGeom(...a); }
export function cabWheelHub(...a) { return (_m || _cold('cabWheelHub')).cabWheelHub(...a); }
export function canvasResidue(...a) { return (_m || _cold('canvasResidue')).canvasResidue(...a); }
export function captureModelMesh(...a) { return (_m || _cold('captureModelMesh')).captureModelMesh(...a); }
export function captureModelTrace(...a) { return (_m || _cold('captureModelTrace')).captureModelTrace(...a); }
export function cliffHeightAt(...a) { return (_m || _cold('cliffHeightAt')).cliffHeightAt(...a); }
export function cliffLatticeSmoke(...a) { return (_m || _cold('cliffLatticeSmoke')).cliffLatticeSmoke(...a); }
export function climbOutClear(...a) { return (_m || _cold('climbOutClear')).climbOutClear(...a); }
export function curtainEndResidue(...a) { return (_m || _cold('curtainEndResidue')).curtainEndResidue(...a); }
export function curtainRoofFtAt(...a) { return (_m || _cold('curtainRoofFtAt')).curtainRoofFtAt(...a); }
export function curtainSegs(...a) { return (_m || _cold('curtainSegs')).curtainSegs(...a); }
export function curtainTopZAt(...a) { return (_m || _cold('curtainTopZAt')).curtainTopZAt(...a); }
export function deadbandStep(...a) { return (_m || _cold('deadbandStep')).deadbandStep(...a); }
export function decoOcclusionSmoke(...a) { return (_m || _cold('decoOcclusionSmoke')).decoOcclusionSmoke(...a); }
export function derivedTrim(...a) { return (_m || _cold('derivedTrim')).derivedTrim(...a); }
export function disposeWindshield(...a) { return (_m || _cold('disposeWindshield')).disposeWindshield(...a); }
export function drawWildScatter(...a) { return (_m || _cold('drawWildScatter')).drawWildScatter(...a); }
export function ensureWindshieldStyles(...a) { return (_m || _cold('ensureWindshieldStyles')).ensureWindshieldStyles(...a); }
export function facePalsSmoke(...a) { return (_m || _cold('facePalsSmoke')).facePalsSmoke(...a); }
export function fasciaKindOf(...a) { return (_m || _cold('fasciaKindOf')).fasciaKindOf(...a); }
export function forecourtDriveSmoke(...a) { return (_m || _cold('forecourtDriveSmoke')).forecourtDriveSmoke(...a); }
export function freeCam(...a) { return (_m || _cold('freeCam')).freeCam(...a); }
export function freeCamState(...a) { return (_m || _cold('freeCamState')).freeCamState(...a); }
export function glDecision(...a) { return (_m || _cold('glDecision')).glDecision(...a); }
export function glLastError(...a) { return (_m || _cold('glLastError')).glLastError(...a); }
export function glLightState(...a) { return (_m || _cold('glLightState')).glLightState(...a); }
export function glWorldInstalled(...a) { return (_m || _cold('glWorldInstalled')).glWorldInstalled(...a); }
export function groundCollisionSmoke(...a) { return (_m || _cold('groundCollisionSmoke')).groundCollisionSmoke(...a); }
export function groundObstructionAt(...a) { return (_m || _cold('groundObstructionAt')).groundObstructionAt(...a); }
export function groundVisibilitySmoke(...a) { return (_m || _cold('groundVisibilitySmoke')).groundVisibilitySmoke(...a); }
export function installGLClouds(...a) { return (_m || _cold('installGLClouds')).installGLClouds(...a); }
export function installGLDispose(...a) { return (_m || _cold('installGLDispose')).installGLDispose(...a); }
export function installGLWorld(...a) { return (_m || _cold('installGLWorld')).installGLWorld(...a); }
export function interiorRenderSmoke(...a) { return (_m || _cold('interiorRenderSmoke')).interiorRenderSmoke(...a); }
export function interiorTally(...a) { return (_m || _cold('interiorTally')).interiorTally(...a); }
export function keepsReach(...a) { return (_m || _cold('keepsReach')).keepsReach(...a); }
export function keyDir(...a) { return (_m || _cold('keyDir')).keyDir(...a); }
export function kitLedges(...a) { return (_m || _cold('kitLedges')).kitLedges(...a); }
export function lastFloorState(...a) { return (_m || _cold('lastFloorState')).lastFloorState(...a); }
export function lastOwnShipMask(...a) { return (_m || _cold('lastOwnShipMask')).lastOwnShipMask(...a); }
export function lastViewState(...a) { return (_m || _cold('lastViewState')).lastViewState(...a); }
export function lightVisibilitySmoke(...a) { return (_m || _cold('lightVisibilitySmoke')).lightVisibilitySmoke(...a); }
export function limbTilt(...a) { return (_m || _cold('limbTilt')).limbTilt(...a); }
export function makeCam(...a) { return (_m || _cold('makeCam')).makeCam(...a); }
export function markRenderSmoke(...a) { return (_m || _cold('markRenderSmoke')).markRenderSmoke(...a); }
export function modelSolid(...a) { return (_m || _cold('modelSolid')).modelSolid(...a); }
export function modelTopAt(...a) { return (_m || _cold('modelTopAt')).modelTopAt(...a); }
export function modelTopZAt(...a) { return (_m || _cold('modelTopZAt')).modelTopZAt(...a); }
export function moonArc(...a) { return (_m || _cold('moonArc')).moonArc(...a); }
export function moonFaceSprite(...a) { return (_m || _cold('moonFaceSprite')).moonFaceSprite(...a); }
export function navMarks(...a) { return (_m || _cold('navMarks')).navMarks(...a); }
export function navMarksOn(...a) { return (_m || _cold('navMarksOn')).navMarksOn(...a); }
export function nearTierSmoke(...a) { return (_m || _cold('nearTierSmoke')).nearTierSmoke(...a); }
export function normalizeWx(...a) { return (_m || _cold('normalizeWx')).normalizeWx(...a); }
export function occludedCount(...a) { return (_m || _cold('occludedCount')).occludedCount(...a); }
export function offCanvasLaterally(...a) { return (_m || _cold('offCanvasLaterally')).offCanvasLaterally(...a); }
export function paintFoot(...a) { return (_m || _cold('paintFoot')).paintFoot(...a); }
export function paintWindshield(...a) { return (_m || _cold('paintWindshield')).paintWindshield(...a); }
export function panelControlRects(...a) { return (_m || _cold('panelControlRects')).panelControlRects(...a); }
export function perchCap(...a) { return (_m || _cold('perchCap')).perchCap(...a); }
export function perchFor(...a) { return (_m || _cold('perchFor')).perchFor(...a); }
export function perchSeat(...a) { return (_m || _cold('perchSeat')).perchSeat(...a); }
export function perchSpot(...a) { return (_m || _cold('perchSpot')).perchSpot(...a); }
export function perchableDepth(...a) { return (_m || _cold('perchableDepth')).perchableDepth(...a); }
export function perfBegin(...a) { return (_m || _cold('perfBegin')).perfBegin(...a); }
export function perfEnabled(...a) { return (_m || _cold('perfEnabled')).perfEnabled(...a); }
export function perfEnd(...a) { return (_m || _cold('perfEnd')).perfEnd(...a); }
export function perfSnapshot(...a) { return (_m || _cold('perfSnapshot')).perfSnapshot(...a); }
export function perfTick(...a) { return (_m || _cold('perfTick')).perfTick(...a); }
export function previewFit(...a) { return (_m || _cold('previewFit')).previewFit(...a); }
export function pushLightningStrike(...a) { return (_m || _cold('pushLightningStrike')).pushLightningStrike(...a); }
export function renderModelPreview(...a) { return (_m || _cold('renderModelPreview')).renderModelPreview(...a); }
export function renderVehiclePreview(...a) { return (_m || _cold('renderVehiclePreview')).renderVehiclePreview(...a); }
export function roofMaterialId(...a) { return (_m || _cold('roofMaterialId')).roofMaterialId(...a); }
export function roofTex(...a) { return (_m || _cold('roofTex')).roofTex(...a); }
export function seaRideAt(...a) { return (_m || _cold('seaRideAt')).seaRideAt(...a); }
export function segFit(...a) { return (_m || _cold('segFit')).segFit(...a); }
export function setBayVehicles(...a) { return (_m || _cold('setBayVehicles')).setBayVehicles(...a); }
export function setObjectTexture(...a) { return (_m || _cold('setObjectTexture')).setObjectTexture(...a); }
export function setTilePlace(...a) { return (_m || _cold('setTilePlace')).setTilePlace(...a); }
export function setWindshieldProfiler(...a) { return (_m || _cold('setWindshieldProfiler')).setWindshieldProfiler(...a); }
export function shapeAdornCost(...a) { return (_m || _cold('shapeAdornCost')).shapeAdornCost(...a); }
export function shapeArchetypeRegistry(...a) { return (_m || _cold('shapeArchetypeRegistry')).shapeArchetypeRegistry(...a); }
export function shapeConstantWarnings(...a) { return (_m || _cold('shapeConstantWarnings')).shapeConstantWarnings(...a); }
export function shapeFootprint(...a) { return (_m || _cold('shapeFootprint')).shapeFootprint(...a); }
export function shapeForModel(...a) { return (_m || _cold('shapeForModel')).shapeForModel(...a); }
export function shapeIsSeedVariant(...a) { return (_m || _cold('shapeIsSeedVariant')).shapeIsSeedVariant(...a); }
export function shapeLinearityError(...a) { return (_m || _cold('shapeLinearityError')).shapeLinearityError(...a); }
export function shapeLodFaces(...a) { return (_m || _cold('shapeLodFaces')).shapeLodFaces(...a); }
export function shapeModelRegistry(...a) { return (_m || _cold('shapeModelRegistry')).shapeModelRegistry(...a); }
export function shapeRenderSmoke(...a) { return (_m || _cold('shapeRenderSmoke')).shapeRenderSmoke(...a); }
export function shapeRoofZ(...a) { return (_m || _cold('shapeRoofZ')).shapeRoofZ(...a); }
export function shapeVal(...a) { return (_m || _cold('shapeVal')).shapeVal(...a); }
export function shapeWireList(...a) { return (_m || _cold('shapeWireList')).shapeWireList(...a); }
export function signFontForTrade(...a) { return (_m || _cold('signFontForTrade')).signFontForTrade(...a); }
export function signFontOf(...a) { return (_m || _cold('signFontOf')).signFontOf(...a); }
export function signKindForce(...a) { return (_m || _cold('signKindForce')).signKindForce(...a); }
export function signStandCensus(...a) { return (_m || _cold('signStandCensus')).signStandCensus(...a); }
export function signTally(...a) { return (_m || _cold('signTally')).signTally(...a); }
export function signTallyZero(...a) { return (_m || _cold('signTallyZero')).signTallyZero(...a); }
export function signalGeomSmoke(...a) { return (_m || _cold('signalGeomSmoke')).signalGeomSmoke(...a); }
export function skyColumnP(...a) { return (_m || _cold('skyColumnP')).skyColumnP(...a); }
export function sortOrderSmoke(...a) { return (_m || _cold('sortOrderSmoke')).sortOrderSmoke(...a); }
export function surfaceBreakup(...a) { return (_m || _cold('surfaceBreakup')).surfaceBreakup(...a); }
export function tagArtwork(...a) { return (_m || _cold('tagArtwork')).tagArtwork(...a); }
export function tagHandList(...a) { return (_m || _cold('tagHandList')).tagHandList(...a); }
export function tagWordList(...a) { return (_m || _cold('tagWordList')).tagWordList(...a); }
export function texEpoch(...a) { return (_m || _cold('texEpoch')).texEpoch(...a); }
export function vehicleBounds(...a) { return (_m || _cold('vehicleBounds')).vehicleBounds(...a); }
export function vehicleFrameDist(...a) { return (_m || _cold('vehicleFrameDist')).vehicleFrameDist(...a); }
export function vehicleRenderSmoke(...a) { return (_m || _cold('vehicleRenderSmoke')).vehicleRenderSmoke(...a); }
export function viewFocal(...a) { return (_m || _cold('viewFocal')).viewFocal(...a); }
export function viewLatFocal(...a) { return (_m || _cold('viewLatFocal')).viewLatFocal(...a); }
export function viewRenderSmoke(...a) { return (_m || _cold('viewRenderSmoke')).viewRenderSmoke(...a); }
export function wallFaceAt(...a) { return (_m || _cold('wallFaceAt')).wallFaceAt(...a); }
export function wallMaterialId(...a) { return (_m || _cold('wallMaterialId')).wallMaterialId(...a); }
export function wallMaterialOf(...a) { return (_m || _cold('wallMaterialOf')).wallMaterialOf(...a); }
export function wallMaterialTable(...a) { return (_m || _cold('wallMaterialTable')).wallMaterialTable(...a); }
export function wallPaletteInfo(...a) { return (_m || _cold('wallPaletteInfo')).wallPaletteInfo(...a); }
export function wallPaletteKeys(...a) { return (_m || _cold('wallPaletteKeys')).wallPaletteKeys(...a); }
export function wallSpanAt(...a) { return (_m || _cold('wallSpanAt')).wallSpanAt(...a); }
export function wallTexMixed(...a) { return (_m || _cold('wallTexMixed')).wallTexMixed(...a); }
export function wallTexSmoke(...a) { return (_m || _cold('wallTexSmoke')).wallTexSmoke(...a); }
export function wildLedges(...a) { return (_m || _cold('wildLedges')).wildLedges(...a); }
export function windshieldHTML(...a) { return (_m || _cold('windshieldHTML')).windshieldHTML(...a); }
export function wireLedge(...a) { return (_m || _cold('wireLedge')).wireLedge(...a); }
export function wireRing(...a) { return (_m || _cold('wireRing')).wireRing(...a); }
export function wireSag(...a) { return (_m || _cold('wireSag')).wireSag(...a); }
export function yachtPadZ(...a) { return (_m || _cold('yachtPadZ')).yachtPadZ(...a); }
export function yachtScopeMount(...a) { return (_m || _cold('yachtScopeMount')).yachtScopeMount(...a); }

