// GENERATED by scripts/shapes/bake-fauna.mjs — never edit by hand.
//
// One row per authored animal, read straight out of content/fauna_models/*.json. These are the
// numbers fauna3d.js builds a mesh from; nothing here is geometry and nothing here is motion —
// a row says what an animal IS, and windshield.js says what it does.
//
// Re-run `npm run fauna:bake` after editing any of those files. `npm run shapes:smoke` fails on
// a stale bake rather than letting the module and the content disagree.
export const BIRD_ROWS = {
  "goose": { "bellyCol": "#c9c2b4", "billCol": "#0e0e11", "billLen": 0.09, "bodyCol": "#6b5f4e", "bodyH": 0.14, "bodyLen": 0.34, "bodyW": 0.125, "cheekCol": "#e8e6df", "chord": 0.3, "flapArc": 0.62, "footLen": 0.07, "headH": 0.065, "headLen": 0.115, "legCol": "#2a2622", "legLen": 0.1, "legW": 0.018, "neckCol": "#16161a", "neckLen": 0.4, "neckRise": 0.34, "neckW": 0.045, "patchCol": "#9a9a8e", "patches": 3, "span": 0.85, "tailLen": 0.14, "tailW": 0.1, "thirdChord": 0.15, "thirdDroop": 0.55, "thirdSide": -1, "thirdSpan": 0.34, "wingCol": "#5a5145", "wingCup": 0.32, "wingSweep": 0.2 },
};
