/**
 * Item Tag Catalog — single source of truth for item behavior.
 *
 * Every behavioral property an item can have is a tag. This catalog documents
 * what each tag does, what shape its value takes, and how the dev panel should
 * render an editor widget for it. The engine reads behavior from tags; this
 * file is the reference so functionality isn't forgotten as the list grows.
 *
 * Dual-mode by design: the dev panel loads this as a classic <script> (so it
 * can't use a bare `export`), while the Node engine imports it for its side
 * effect and reads the global. Both land on `globalThis.TAG_CATALOG`.
 *
 * shape — drives the dev-panel input widget and serialization:
 *   text    free text (textarea)
 *   flag    valueless marker (stored as `true`)
 *   int     integer
 *   enum    one of `options`
 *   range   { min, max }
 *   hot     heal-over-time { amount, duration_seconds }
 *   statmap JSON object of key -> number (small JSON textarea)
 *
 * scope — storage semantics for the engine: 'class' tags live on the item
 * template (items.tags); 'instance' tags are presence-only flags on a carried
 * item (player_inventory.custom_data); 'furniture' tags live on a furniture row
 * (furniture.flags). They all surface via tagsOf() the same way.
 *
 * targets — OPTIONAL array controlling which dev-panel editors offer the tag:
 * subset of ['item','furniture']. When present it overrides the default derived
 * from scope, so a single tag can be attachable on both items and furniture
 * (e.g. broadcast_receiver). When absent, applicability is derived from scope
 * (class → item, furniture → furniture, instance → neither; instance flags are
 * runtime-only and never builder-attached). Use tagTargets()/tagAppliesTo().
 */
(function (global) {
  const TAG_CATALOG = {
    // --- Core / identity ---
    description: { label: 'Description', shape: 'text', scope: 'class', group: 'Core',
      help: 'Free text shown on examine / look <item>.' },
    quest_item: { label: 'Quest Item', shape: 'flag', scope: 'class', group: 'Core',
      help: 'Cannot be dropped or sold.' },
    unique: { label: 'Unique', shape: 'flag', scope: 'class', group: 'Core',
      help: 'Prevents stacking. Items stack by default; tag an item Unique to keep each as its own row.' },

    // --- Type markers (filtering / flavor / routing) ---
    weapon: { label: 'Weapon', shape: 'flag', scope: 'class', group: 'Type',
      help: 'Marks a combat weapon. The equipped item with this tag is used when you attack.' },
    consumable: { label: 'Consumable', shape: 'flag', scope: 'class', group: 'Type',
      help: 'Usable via use / eat / drink. Gates the consumable-effect path.' },
    drug: { label: 'Drug', shape: 'flag', scope: 'class', group: 'Type',
      help: 'Marks a drug (visibility/flavor). Mechanics still come from the drugs table joined by item_id.' },
    material: { label: 'Material', shape: 'flag', scope: 'class', group: 'Type',
      help: 'Crafting input. No direct use.' },
    currency: { label: 'Currency', shape: 'flag', scope: 'class', group: 'Type',
      help: 'Credit chip flavor marker. Use grants_credits for the actual payout.' },
    misc: { label: 'Misc', shape: 'flag', scope: 'class', group: 'Type',
      help: 'Catch-all flavor marker for key items, artifacts, accessories.' },

    // --- Equipment ---
    slot: { label: 'Equip Slot', shape: 'enum', scope: 'class', group: 'Equipment',
      options: ['head', 'torso', 'hands', 'legs', 'feet', 'weapon_hand', 'accessory'],
      help: 'Body slot this equips to. Presence of this tag is what makes an item equippable.' },
    armor_soak: { label: 'Armor Soak', shape: 'statmap', scope: 'class', group: 'Equipment',
      help: 'Per-damage-type soak, e.g. { "kinetic": 4, "energy": 1 }. Used when this piece covers the struck body part.' },
    insulation: { label: 'Insulation', shape: 'int', scope: 'class', group: 'Equipment',
      help: 'Thermal insulation in °C. Added to ambient temperature to determine effective temperature for body heat calculations. Stacks across all equipped clothing.' },
    bulkiness: { label: 'Bulkiness', shape: 'int', scope: 'class', group: 'Equipment',
      help: 'Physical thickness of the garment, 1 (paper-thin underwear) to 5 (rigid plate armor). Determines whether the item fits in a layer alongside others.' },
    layer: { label: 'Layer', shape: 'enum', scope: 'class', group: 'Equipment',
      options: ['underwear', 'outerwear', 'armor'],
      help: 'Which of the three worn layers this piece occupies on a body slot (underwear < outerwear < armor, innermost to outermost). Only one item per slot+layer; others see only your outermost layer. Ignored for weapon_hand and accessory. Defaults to outerwear if unset.' },
    covers: { label: 'Also Covers', shape: 'list', scope: 'class', group: 'Equipment',
      help: 'Extra body slots this one garment fills, e.g. ["legs"] on a torso jumpsuit — a single piece that occupies both slots at its layer. Equipping it clears (and is cleared by) anything in the covered slots at that layer; its insulation/armor apply to every covered slot.' },
    gets_wet: { label: 'Gets Wet', shape: 'flag', scope: 'class', group: 'Equipment',
      help: 'Accumulates wetness (0–100) when worn in rain or snow. Wet clothing lowers cooling thresholds and speeds heat loss.' },
    sealed: { label: 'Sealed (Respirator)', shape: 'flag', scope: 'class', group: 'Equipment',
      help: 'Seals the airway (gas mask / respirator). While equipped, blocks the ashfall choking hazard. Any one sealed item suffices.' },
    auto_equip: { label: 'Auto-Equip', shape: 'flag', scope: 'class', group: 'Equipment',
      help: 'When obtained, this item automatically equips to its designated slot if that slot is empty.' },
    stat_bonus: { label: 'Stat Bonus', shape: 'statmap', scope: 'class', group: 'Equipment',
      help: 'Passive stat bumps, e.g. { "stat_brawn": 3 }. Use new stat keys (stat_brawn/reflexes/endurance/brains/cool).' },
    requires: { label: 'Requirements', shape: 'statmap', scope: 'class', group: 'Equipment',
      help: 'Stat gates to equip, e.g. { "stat_brawn": 6 }. Each key must be met or exceeded.' },

    // --- Combat ---
    damage: { label: 'Damage', shape: 'range', scope: 'class', group: 'Combat',
      help: 'Weapon damage roll range { min, max }.' },
    weapon_skill: { label: 'Weapon Skill', shape: 'enum', scope: 'class', group: 'Combat',
      options: ['fists', 'blades', 'clubs', 'firearms', 'science'],
      help: 'Which combat skill earns XP and routes the attack.' },
    damage_type: { label: 'Damage Type', shape: 'enum', scope: 'class', group: 'Combat',
      options: ['kinetic', 'edged', 'energy', 'fire', 'radiation'],
      help: 'Physical damage category. Used to index per-part armor soak on defender.' },
    status_chance: { label: 'Status Chance', shape: 'statmap', scope: 'class', group: 'Combat',
      help: 'Chance to inflict a status, e.g. { "stunned": 0.3 }.' },
    butchering: { label: 'Butchering Tool', shape: 'flag', scope: 'class', group: 'Combat',
      help: 'Carrying any item with this tag lets you butcher corpses (knives, blades, etc.).' },
    demolition: { label: 'Demolition Tool', shape: 'flag', scope: 'class', group: 'Combat',
      help: 'Marks a heavy tool/weapon (sledgehammer, cutting torch, breaching charge) capable of damaging armoured industrial infrastructure — generators and junction boxes. The main power plant can ONLY be damaged by an equipped item with this tag.' },

    // --- Consumable effects ---
    use_message: { label: 'Use Message', shape: 'text', scope: 'class', group: 'Consumable',
      help: 'Flavour line shown when the item is consumed via use / eat / drink; falls back to a plain default.' },
    restore_hp: { label: 'Restore HP', shape: 'int', scope: 'class', group: 'Consumable',
      help: 'Instant HP change (can be negative).' },
    restore_hunger: { label: 'Restore Hunger', shape: 'int', scope: 'class', group: 'Consumable',
      help: 'Restores the hunger meter (capped at 100).' },
    restore_thirst: { label: 'Restore Thirst', shape: 'int', scope: 'class', group: 'Consumable',
      targets: ['item', 'furniture'],
      help: 'Restores the thirst meter (capped at 100). On a water-source furniture, sets how much a drink restores.' },
    restore_radiation: { label: 'Restore Radiation', shape: 'int', scope: 'class', group: 'Consumable',
      help: 'Adds/removes radiation (RadAway uses -20).' },
    restore_sanity: { label: 'Restore Sanity', shape: 'int', scope: 'class', group: 'Consumable',
      help: 'Adjusts Sanity (drinks restore it; some items drop it).' },
    grants_credits: { label: 'Grants Credits', shape: 'int', scope: 'class', group: 'Consumable',
      help: 'Currency granted on use (credit chips).' },
    heal_over_time: { label: 'Heal Over Time', shape: 'hot', scope: 'class', group: 'Consumable',
      help: 'Gradual heal { amount, duration_seconds }, ticks once/min, stacks if re-used.' },
    well_fed: { label: 'Well-Fed', shape: 'flag', scope: 'class', group: 'Consumable',
      help: 'Grants the Well-Fed buff (faster HP regen) for 10 minutes.' },
    hydrating: { label: 'Hydrating', shape: 'flag', scope: 'class', group: 'Consumable',
      help: 'Grants the Hydrated buff (faster radiation decay) for 10 minutes.' },
    laced_drug: { label: 'Laced Drug', shape: 'text', scope: 'class', group: 'Consumable',
      help: 'Drug id (e.g. drug_alcohol) this consumable applies as a carrier — the drug\'s onset/effects run, but its own instant restores are skipped in favor of this item\'s restore_* tags.' },
    laced_potency: { label: 'Laced Potency', shape: 'int', scope: 'class', group: 'Consumable',
      help: 'Multiplier applied to the laced drug\'s potency (e.g. 1.6 for a strong pour). Pairs with laced_drug.' },

    // --- Container ---
    container: { label: 'Container Capacity', shape: 'int', scope: 'class', group: 'Container',
      help: 'Marks this item as a container. Value is the max total weight it can hold. Contents count at 75% of their weight while carried.' },
    fillable: { label: 'Fillable Capacity', shape: 'int', scope: 'class', group: 'Container',
      help: 'Marks this item as a fillable fluid container. Value is the capacity in fluid units (a neutral volume). Fill at a water source; drink to consume the fluid. How much a fluid restores is a property of the fluid, not the container.' },

    // --- Gear ---
    flashlight: { label: 'Flashlight', shape: 'flag', scope: 'class', group: 'Gear',
      help: 'Marks this item as a battery-powered handheld flashlight. LIGHT / UNLIGHT toggle it; RELOAD swaps in a battery. A lit, charged flashlight makes dark rooms readable for the holder. Pair with the Unique tag so each unit keeps its own on/charge state.' },
    battery: { label: 'Battery', shape: 'flag', scope: 'class', group: 'Gear',
      help: 'Marks this item as a power cell. Consumed by RELOAD to recharge a flashlight (or other battery-powered device).' },
    hack_device: { label: 'Hacking Device', shape: 'flag', scope: 'class', group: 'Gear',
      help: 'Marks this item as an intrusion deck. Carrying one (in hand, not in a container) is the tool gate for HACK on hololocked doors and for jacking ATM terminals; it is also classed as contraband when jailed. Pair with the Unique tag so each deck keeps its own condition — failed breaches damage it.' },
    fishing_rod: { label: 'Fishing Rod', shape: 'flag', scope: 'class', group: 'Gear',
      help: 'Marks this item as a fishing rod. Carrying one (in hand, not in a container) is the tool gate for FISH at a water-adjacent zone. Pair with the Unique tag so each rod keeps its own condition — a botched reel can snap it.' },
    bait: { label: 'Bait', shape: 'flag', scope: 'class', group: 'Gear',
      help: 'Marks this item as fishing bait. Optional while FISHing: one is consumed per catch, shifting the odds toward better catches and unlocking bait-gated fish. A more specific sub-tag (e.g. bait_bloodworm) can gate particular catches.' },
    mining_tool: { label: 'Mining Tool', shape: 'flag', scope: 'class', group: 'Gear',
      help: 'Marks this item as a mining tool (pick, drill, breaker bar). Carrying one (in hand, not in a container) is the tool gate for MINE at a zone with an ore deposit. Pair with the Unique tag so each tool keeps its own condition.' },

    // --- Locks ---
    "lock:hololock": { label: 'Holographic Lock', shape: 'statmap', scope: 'class', group: 'Hardware', help: 'Electronic holographic authorization matrix.' },
    "lock:keycardlock": { label: 'Magnetic Keycard Reader', shape: 'statmap', scope: 'class', group: 'Hardware', help: 'Magnetic reader checking passcode clearance profiles.' },

    // --- Installation Kits ---
    "lockkit:hololock": { label: 'Hololock Installation Kit', shape: 'flag', scope: 'class', group: 'Tools', help: 'Consumable installation kit used to deploy a holographic lock setup onto a door or frame.' },
    "lockkit:keycardlock": { label: 'Keycard Lock Installation Kit', shape: 'flag', scope: 'class', group: 'Tools', help: 'Consumable installation kit used to deploy a magnetic keycard reader onto a door or frame.' },

    // --- Broadcast ---
    broadcast_receiver: { label: 'Broadcast Receiver', shape: 'flag', scope: 'class', group: 'Broadcast',
      targets: ['item', 'furniture'],
      help: 'Item or furniture can be tuned to a broadcast channel.' },
    broadcast_transmitter: { label: 'Broadcast Transmitter', shape: 'flag', scope: 'class', group: 'Broadcast',
      targets: ['item', 'furniture'],
      help: 'Item or furniture is a camera or microphone (broadcast source).' },
    broadcast_device_type: { label: 'Device Type', shape: 'enum', scope: 'class', group: 'Broadcast',
      targets: ['item', 'furniture'],
      options: ['tv', 'radio', 'security_monitor', 'portable_monitor', 'camera'],
      help: 'Controls how broadcast content is formatted for this device.' },
    media_deck: { label: 'Media Deck', shape: 'flag', scope: 'furniture', group: 'Broadcast',
      help: 'This furniture is a media cassette deck. Players can load/eject cassette items. Broadcasts in deck_cassettes play in the zone instead of scheduled programming.' },
    emergency_deck: { label: 'Emergency Deck', shape: 'flag', scope: 'furniture', group: 'Broadcast',
      help: "The Echelon's special MediaDeck. AIREMERGENCY (admin) seizes EVERY tuned television in Architect with this deck's loaded bulletin (deck_active); ENDEMERGENCY releases them. The single global counterpart to the per-deck pirate override." },
    teleporter: { label: 'Teleporter', shape: 'flag', scope: 'furniture', group: 'Broadcast',
      help: "A concealed teleporter (yacht plugin). USE it to jump to flags.teleport_target — but only for an approved player; to anyone else it behaves as an ordinary closet. Pairs with teleport_target." },
    teleport_target: { label: 'Teleport Target', shape: 'text', scope: 'furniture', group: 'Broadcast',
      help: 'Destination zone id a teleporter furniture jumps an approved user to.' },
    concealed: { label: 'Concealed', shape: 'flag', scope: 'furniture', group: 'Broadcast',
      help: 'Cosmetic marker: this furniture is a hidden fixture whose true function is not advertised.' },
    media_cassette: { label: 'Media Cassette', shape: 'flag', scope: 'class', group: 'Broadcast',
      help: 'This item is a cassette tape. It should also have flags.broadcast_id pointing to a media_broadcasts row.' },

    // --- Furniture capabilities (presence-only, on a furniture row) ---
    water_source: { label: 'Water Source', shape: 'flag', scope: 'furniture', group: 'Capabilities',
      help: 'Players can drink from and wash at this furniture. Enables the water-plugin verbs (drink/wash). The verb is blind to what the furniture is — sink, fountain, well, leaking pipe — it only asks for this capability.' },
    bulletin: { label: 'Bulletin Board', shape: 'flag', scope: 'furniture', group: 'Capabilities',
      help: 'Players can READ this furniture to see the server leaderboard — the top 5 survivors ranked by total XP (ties broken by older account first).' },
    toilet: { label: 'Toilet', shape: 'flag', scope: 'furniture', group: 'Capabilities',
      help: 'Players can sit and relieve themselves here (pee / poop / flush) with privacy. The verbs are blind to what the furniture is — stall, latrine, bucket — they only ask for this capability.' },
    cosmetic_machine: { label: 'Cosmetic Machine', shape: 'flag', scope: 'furniture', group: 'Capabilities',
      help: 'Players can change their appearance here (the morphex/biosculpt verbs). The verb only asks for this capability, not a specific object_type.' },

    // --- Instance flags (presence-only, on a carried item) ---
    broken: { label: 'Broken', shape: 'flag', scope: 'instance', group: 'Instance',
      help: 'Per-item state flag set on a carried instance.' },
    cursed: { label: 'Cursed', shape: 'flag', scope: 'instance', group: 'Instance',
      help: 'Per-item state flag set on a carried instance.' },

    // --- System tags (backfilled from live data by the tag-key sweep; each is
    // read by the named system. bait_* sub-tags are a parameterized family —
    // see the fishing plugin — and are exempted from catalog validation.) ---
    amp_cassette: { label: 'Amp Cassette', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Amp-plugin music cassette. Playable in an amp.' },
    automates: { label: 'Automates Step', shape: 'enum', scope: 'class', group: 'Systems',
      options: ['charge', 'mix', 'pour', 'stir', 'heat', 'rhythm'],
      help: 'Synthesis lab equipment: which splice stage this apparatus automates (SPLICE_STAGES).' },
    interactions: { label: 'Interactions', shape: 'list', scope: 'class', group: 'Systems',
      help: 'Interactable verbs this object offers, e.g. ["switch","sit"]. Each entry surfaces as a present tag via tagsOf() for the specialized-action registry.' },
    battery_max: { label: 'Battery Capacity', shape: 'int', scope: 'class', group: 'Systems',
      help: 'Portable generator battery capacity in kW-minutes (generator plugin / power sim).' },
    boat: { label: 'Boat', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Carrying this rides the player across water dry — no swim stamina cost, no wetness/cold (swimming plugin).' },
    rebreather: { label: 'Rebreather', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Carrying/wearing this supplies air underwater — no breath timer, so you never drown from lack of air (swimming plugin). Stamina still applies.' },
    broadcast_id: { label: 'Broadcast ID', shape: 'text', scope: 'class', group: 'Systems',
      help: 'media_broadcasts row this cassette plays (pairs with media_cassette).' },
    component: { label: 'Component', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Salvaged tech component — crafting/repair input.' },
    concealment_base: { label: 'Concealment Base', shape: 'int', scope: 'class', group: 'Systems',
      help: 'Surveillance device: base difficulty to spot it once planted.' },
    contraband: { label: 'Contraband', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Illegal to carry through government checkpoints; confiscated to the evidence locker on arrest (govgate/jail).' },
    cook_kit: { label: 'Cook Kit', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Portable drug-synthesis kit (synthesis plugin).' },
    device_kind: { label: 'Device Kind', shape: 'text', scope: 'class', group: 'Systems',
      help: 'Surveillance device type: audio_sensor, motion_sensor, drone, jammer, camera…' },
    device_tier: { label: 'Device Tier', shape: 'int', scope: 'class', group: 'Systems',
      help: 'Surveillance device quality tier (1–3).' },
    document: { label: 'Document', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Readable document marker (NPC reactions / flavor).' },
    hack_difficulty: { label: 'Hack Difficulty', shape: 'int', scope: 'class', group: 'Systems',
      help: 'Difficulty of hacking this device (ATM / hackable gear).' },
    lab_upgrade: { label: 'Lab Upgrade', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Synthesis lab upgrade marker. Not currently read by engine code.' },
    metal: { label: 'Metal', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Metal material marker (infrastructure repair / crafting).' },
    mule_crate: { label: 'Mule Crate', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Smuggling cargo crate (smuggle plugin).' },
    prologue_holocaster: { label: 'Prologue Holocaster', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'The prologue quest holocaster (prologue plugin).' },
    radioactive: { label: 'Radioactive', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Radioactive cargo/material hazard marker (flight biomes).' },
    raw_drug: { label: 'Raw Drug', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Uncut drug brick — smuggling/flight contract cargo, checkpoint contraband.' },
    reagent: { label: 'Reagent', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Drug-synthesis chemical input (synthesis plugin).' },
    security_gear: { label: 'Security Gear', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Plantable surveillance gear (surveillance plugin).' },
    song_id: { label: 'Song ID', shape: 'text', scope: 'class', group: 'Systems',
      help: 'audio_samples row this music item plays (audio plugin).' },
    specter_program: { label: 'SPECTER Program', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'The SPECTER surveillance tablet-app item (surveillance plugin).' },
    piracy_firmware: { label: 'Pirate Firmware', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Firmware drive `use`d to flash signal-piracy onto the tablet; then `pirate` a media deck (broadcast plugin).' },
    spy_deck: { label: 'Spy Deck', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Surveillance hub deck — reviews planted-device feeds.' },
    stackable: { label: 'Stackable (legacy)', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Legacy no-op: items stack by default (unique opts out). Kept so existing content validates.' },
    trophy: { label: 'Trophy', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Sports-league trophy item.' },
    valuable: { label: 'Valuable', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'High-value flavor marker. Not currently read by engine code.' },
    wired: { label: 'Wired', shape: 'flag', scope: 'class', group: 'Systems',
      help: 'Wired/connected device state marker (infrastructure/graph systems).' },

    // --- Zone tags (scope 'zone': the zones.flags bag, validated on zone save) ---
    sanctuary: { label: 'Sanctuary', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Civilization carve-out — attach DELIBERATELY. Grants combat protection via the protection substrate, safe sleep, AI safe-flee targeting, and suppresses hostile spawns. (Not auto-derived from the legacy is_safe_zone column, which was stamped on most of the map.)' },
    allow_sleep: { label: 'Allow Sleep', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Permit `sleep` in this zone WITHOUT the full sanctuary bundle — grants safe-zone-rate rest but no combat protection / forcefield / spawn suppression. For places like the holding cell where you can doze but stay exposed.' },
    radiation: { label: 'Radiation', shape: 'int', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Ambient radiation 0-100. Players gain floor(value × 0.1) rads on entering the zone. Absent = clean. Replaces the radiation_level column.' },
    danger: { label: 'Danger Override', shape: 'enum', scope: 'zone', group: 'Zone: Law & Hazard',
      options: ['safe', 'low', 'medium', 'high', 'lethal'],
      help: 'Manual danger override. Danger is normally inferred from the zone\'s enemy spawns — set this only for hazard-flavor zones with no spawn rows (rad fields, scripted horrors).' },
    lawless: { label: 'Lawless', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Crimes here raise no heat/wanted (surveillance).' },
    unsurveilled: { label: 'Unsurveilled', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Off the Architect\'s grid — the surveillance witness roll (cameras/cops/bystanders) short-circuits to unseen here, so no crime is ever witnessed and no heat is earned. The Long Watch bunker uses this to stay hidden from the machine.' },
    safehouse: { label: 'Safehouse', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Actively launders wanted heat: unseen time bleeds a wanted star three times as fast as lying low on the street. Pair with unsurveilled/sanctuary for a true refuge.' },
    no_spawn: { label: 'No Spawns', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Suppress enemy spawns in this zone.' },
    claimable: { label: 'Claimable Territory', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Corps territory override: force this zone claimable. Absent = derived (claimable when inferred danger isn\'t safe, never apartments).' },
    claimable_asset: { label: 'Claimable Business', shape: 'text', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Corporate Assets: a corp can take this storefront over with "corp asset claim". Value is the asset type key (restaurant, casino, fence, gun_shop, clinic, chem_supply). Needs a vendor NPC in the zone for the sales cut.' },
    aa_site: { label: 'AA Emplacement', shape: 'flag', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Exposed anti-aircraft emplacement (aa-sites plugin): the standable tile that fires on overflying aircraft and can be assaulted on foot. Pairs with an aa_sites row.' },
    aa_bunker: { label: 'AA Bunker', shape: 'text', scope: 'zone', group: 'Zone: Law & Hazard',
      help: 'Interior bunker of an AA emplacement (aa-sites plugin). Value is the linked AA site id (e.g. aa_clone_guard).' },

    is_interior: { label: 'Interior', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Indoors — weather/temperature/lighting use the interior model.' },
    is_dreamzone: { label: 'Dreamzone', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Off-map hallucination zone the trip plugin teleports a mind into (map_dream, no exits). Kept off the minimap; login bounces anyone stranded here by a restart.' },
    is_apartment: { label: 'Apartment', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Rentable apartment zone (RENT / LOCK / SLEEP). Pairs with an apartments row.' },
    is_building: { label: 'Building', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Building facade/root — groups interior zones into one building (junction-box power scope, entrance discovery).' },
    facade: { label: 'Facade (Non-Standable)', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'OPT-IN pass-through building tile: stepping onto it auto-forwards into the building\'s interior entry zone (needs an interior map parented on this zone); OUT from inside lands on world_exit_zone. Without this tag a building tile is a normal standable zone — do NOT put it on street tiles that host a building.' },
    building_name: { label: 'Building Name', shape: 'text', scope: 'zone', group: 'Zone: Structure',
      help: 'Display name of the enclosing building.' },
    building_type: { label: 'Building Type', shape: 'text', scope: 'zone', group: 'Zone: Structure',
      help: 'Building category (bar, hotel, store, grocery, …) — controls entrance-discovery flavor text.' },
    floors: { label: 'Floors (Storeys)', shape: 'number', scope: 'zone', group: 'Zone: Structure',
      help: 'Explicit storey count for the flight-sim skyline — overrides the per-building-type default so a landmark tower stands taller (or shorter). Read by the windshield building-height formula.' },
    world_exit_zone: { label: 'World Exit Zone', shape: 'text', scope: 'zone', group: 'Zone: Structure',
      help: 'Exterior seam zone for this building — where OUT ultimately lands.' },
    entrance: { label: 'Entrance Direction', shape: 'text', scope: 'zone', group: 'Zone: Structure',
      help: 'Authored door side (north/south/east/west) for the map entrance arrow — read by buildingEntranceDir. Baked once from the road graph, NOT inferred at runtime, so terrain painting can never relocate a door. The interior out-exit must mirror this.' },
    utility_room: { label: 'Utility Room', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Building utility room (the junction box lives here).' },
    elevator: { label: 'Elevator', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Elevator car zone.' },
    elevator_floors: { label: 'Elevator Floors', shape: 'list', scope: 'zone', group: 'Zone: Structure',
      help: 'Floor list for the elevator, e.g. [{ "n": 50, "zone": "zone_x", "label": "Concourse" }].' },
    hide_exits: { label: 'Hide Exits', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Suppress the exit/room/building list in the room description; graph (movement, pathfinding, minimap) is untouched. Elevator cars use it so the floor panel is the sole exit UI.' },
    open_sky: { label: 'Open Sky', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Outdoor zone aircraft can overfly/land; on interiors, an open roof.' },
    water: { label: 'Water', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Deep/open water. Swimmable on foot (costs stamina, soaks + chills you); a boat-tagged item rides you across dry.' },
    underwater: { label: 'Underwater', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'A submerged tile below a surface water tile (link up/down). Always submerged (a boat does not help), colder, and dark; starts a breath timer that drowns you when it runs out.' },
    water_temp_c: { label: 'Water Temperature (°C)', shape: 'number', scope: 'zone', group: 'Zone: Structure',
      help: 'Override the temperature a submerged swimmer here drifts toward (default: 12°C surface / 7°C underwater). Lower = hypothermia faster; e.g. 26 for a warm lagoon.' },
    vessel: { label: 'Vessel (boardable from water)', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'This water tile is a boat you can embark/disembark from the water (needs an `in` exit to the vessel interior). The Echelon uses it; future boats too.' },
    always_lit: { label: 'Always Lit', shape: 'flag', scope: 'zone', group: 'Zone: Structure',
      help: 'Never dark regardless of power/time.' },
    rest_multiplier: { label: 'Rest Multiplier', shape: 'number', scope: 'zone', group: 'Zone: Structure',
      help: 'Scales both stamina regen and HP knit-back for anyone resting in this zone (restRegenTick in gameLoop.js). Default 1. Comfort zones raise it — Solenne units 1.5, penthouse 2.0.' },
    terrain: { label: 'Terrain', shape: 'enum', options: ['water', 'road', 'dirt_road', 'asphalt', 'concrete', 'grass', 'park', 'dirt', 'sand', 'gravel', 'dock', 'scrub', 'redrock', 'ash', 'marsh'], scope: 'zone', group: 'Zone: Structure',
      help: 'Ground surface for the map/minimap and the flight-sim ground tint — the authoritative source for zoneTerrain (overrides the inferred surface). Painted in the dev panel: Maps → Terrain mode. Road AND dirt_road tiles auto-tile their connector piece from adjacent road/dirt_road tiles; dirt_road renders as a graded packed-dirt track (brown, wheel ruts, no paint) rather than paved asphalt.' },
    park_feature: { label: 'Park Feature', shape: 'enum', options: ['grove', 'pond', 'benches', 'flowerbeds', 'path'], scope: 'zone', group: 'Zone: Structure',
      help: 'On a "park" terrain tile, forces which flight-sim park dressing it draws (grove/pond/benches/flowerbeds/path) so a park can be laid out symmetrically. Unset → chosen from the tile position hash.' },

    ascendant_campus: { label: 'Ascendant Campus', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'Marks a world tile as part of the Ascendant stronghold campus (western frontier) — used for ambience and faction framing.' },
    ascension_gate: { label: 'Ascension Gate', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'The gated entrance tile into the Ascendant campus.' },
    ascendant_inner: { label: 'Ascendant Inner Sanctum', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'The Spire sanctum — deepest Ascendant interior, reserved for the highest standing.' },
    ascendant_vats: { label: 'Ascendant Vats', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'The cloning/regrowth hall within The Vats.' },
    ascendant_registry: { label: 'Ascendant Registry', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'The Vats registry desk — intake/enrolment room.' },
    augment_clinic: { label: 'Augment Clinic', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'A room where cybernetic augments can be installed (Chrome Clinic). Read by the augments plugin.' },
    assurance_policy: { label: 'Cortical Assurance Desk', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'A desk that sells prepaid cortical-backup restores (the secret Halcyon front). Enables the `policy` verb. Read by the augments plugin.' },
    architect_uplink: { label: 'Architect Uplink', shape: 'flag', scope: 'zone', group: 'Zone: Ascendant',
      help: 'The Architect Shrine uplink chamber — the Ascendants’ direct line to the Architect.' },

    yacht: { label: 'Yacht (Access-Gated)', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'Marks a zone as part of an invite-only vessel (the yacht plugin). Boarding on foot is blocked for the uninvited; an uninvited player who ends up here anyway (teleport/glitch) is smitten on entry.' },
    echelon: { label: 'The Echelon', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'Identity flag for The Echelon admin superyacht — distinguishes its zones from any future yacht.' },
    echelon_bridge: { label: 'Echelon Bridge', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'The helm room: the SAIL/HELM verb only works while standing here.' },
    echelon_view: { label: 'Echelon Overlook', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'A deck from which you can LOOK out across the Basin (stern lounge, stair landing).' },
    echelon_suite: { label: "Echelon Owner's Suite", shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: "Cyd's private quarters — owner-gated behind the suite hatch; hosts the MIS-gated dancers." },
    echelon_helipad: { label: 'Echelon Helipad', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'The stern landing pad — a Dragonfly (VTOL) can set down here to embark/disembark.' },
    echelon_sundeck: { label: 'Echelon Sun Deck', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'The open-air top-deck lounge with the jacuzzi; beckoned consorts suntan / soak / lounge here (consort plugin area-life).' },
    echelon_broadcast: { label: 'Echelon Broadcast Deck', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'The lower-deck studio housing the special emergency MediaDeck that overrides every tuned TV in the city.' },
    pier: { label: 'Pier / Jetty', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'A shoreline docking point. When a yacht (the Echelon) comes to rest on the water tile alongside, a gangway exit is auto-wired between them so invited players can board or step ashore.' },
    naval_ambience: { label: 'Naval Ambience', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'Open-deck soundscape: gulls, surf and rigging play here (client yacht-ambience). Set on open-air deck zones so the naval bed is heard on deck but not in the suites/engineering.' },
    engine_ambience: { label: 'Engine Ambience', shape: 'flag', scope: 'zone', group: 'Zone: Echelon',
      help: 'Engine-room rumble plays here (client yacht-ambience), swelling while she makes way (yacht_underway). Set on the engine spaces.' },
    heading: { label: 'Heading (deg)', shape: 'int', scope: 'zone', group: 'Zone: Echelon',
      help: 'RUNTIME-only: the vessel\'s last steered course in degrees (0=N, bow-north), injected onto the live Echelon exterior zone by the yacht plugin from the persisted world flag. Not authored in content — catalogued so the persisted state validates on the zone-flags sweep.' },

    aircraft_cabin: { label: 'Aircraft Cabin', shape: 'text', scope: 'zone', group: 'Zone: Aircraft',
      help: 'Marks a zone as an interior cabin room of a walkable aircraft (the craft-type id, e.g. "leviathan"). The flight plugin binds these coordinate-free rooms to the live aircraft and lets occupants walk between them; the move gate keeps world exits sealed while airborne.' },
    cabin_entry: { label: 'Cabin Entry', shape: 'flag', scope: 'zone', group: 'Zone: Aircraft',
      help: 'The room boarders arrive in when they embark a walkable aircraft (and are set down near on deplane). One per cabin; mirrors the cabin map\'s entry_zone_id.' },
    cabin_window: { label: 'Cabin Window', shape: 'flag', scope: 'zone', group: 'Zone: Aircraft',
      help: 'A cabin room with windows: the WINDOW verb opens the through-hull moving-world view from here (reuses the passenger windshield fed by the live map window).' },
    flightdeck: { label: 'Flight Deck', shape: 'flag', scope: 'zone', group: 'Zone: Aircraft',
      help: 'The cockpit room of a walkable aircraft: where the NPC (or player) pilot flies. Home of the TAKE CONTROLS / HAND OFF verbs and the NAV course console (later phases).' },
    home_slots: { label: 'Home Slots', shape: 'list', scope: 'zone', group: 'Zone: Aircraft',
      help: 'Authored decor anchors a walkable-base room offers, each { id, kind, label } — the owner fills them from the decor catalog (custom_data.home.slots). The shell defines the anchors; per-owner choices are runtime overlays, never zone edits.' },

    district: { label: 'District Override', shape: 'text', scope: 'zone', group: 'Zone: Identity',
      help: 'Override the derived district key (normally from the zone-id prefix; see server/engine/districts.js).' },
    artery: { label: 'Artery (Street Names)', shape: 'list', scope: 'zone', group: 'Zone: Identity',
      help: 'Major street name(s) this zone lies on, e.g. ["The Haul Road"]. Drives traffic ambience and map street labels.' },
    street_life: { label: 'Street Life', shape: 'flag', scope: 'zone', group: 'Zone: Identity',
      help: 'Opts the zone into lived-in ambient NPC street-life routines.' },
    intro_lore: { label: 'Intro Lore', shape: 'text', scope: 'zone', group: 'Zone: Identity',
      help: 'One-time lore text shown on a player\'s first visit.' },
    planner: { label: 'Planner Blueprint', shape: 'text', scope: 'zone', group: 'Zone: Identity',
      help: 'Provenance marker: the blueprint id that generated this zone (tools/zone-planner). Re-running that blueprint may reassert this zone\'s grid position and planner-drawn exits.' },
    region_id: { label: 'Region (spatial)', shape: 'text', scope: 'zone', group: 'Zone: Identity',
      help: 'Spatial region membership: the regions.id this tile belongs to (dev-panel World Editor). Distinct from "District Override" above (land-use). Selecting/moving a region acts on every zone sharing this id.' },
    icon: { label: 'Map Icon', shape: 'text', scope: 'zone', group: 'Zone: Identity',
      help: 'Name of an SVG in client/game/assets/zone-icons/ (without .svg) drawn on the minimap tile in place of the marker glyph, e.g. "store". The file is the asset; this just references it.' },
    prologue: { label: 'Prologue', shape: 'flag', scope: 'zone', group: 'Zone: Identity',
      help: 'Part of the prologue instance.' },

    scavenging_table_id: { label: 'Scavenging Table', shape: 'text', scope: 'zone', group: 'Zone: Systems',
      help: 'Loot table id for SCAVENGE here.' },
    fishing_table_id: { label: 'Fishing Table', shape: 'text', scope: 'zone', group: 'Zone: Systems',
      help: 'Scavenging-table id used for FISH here.' },
    mining_table_id: { label: 'Mining Table', shape: 'text', scope: 'zone', group: 'Zone: Systems',
      help: 'Scavenging-table id used for MINE here.' },
    checkpoint_cfg: { label: 'Checkpoint Config', shape: 'text', scope: 'zone', group: 'Zone: Systems',
      help: 'Security-checkpoint config object driving the checkpoint plugin: { guards, checks:[wanted|contraband], wantedMode:hard|bluff, and one entry predicate insideFlag|fromFlag|fromDistrict }.' },
    gov_checkpoint: { label: 'Gov Checkpoint', shape: 'flag', scope: 'zone', group: 'Zone: Systems',
      help: 'Government checkpoint — contraband scan on pass-through.' },
    gov_enclave: { label: 'Gov Enclave', shape: 'flag', scope: 'zone', group: 'Zone: Systems',
      help: 'Inside the government enclave.' },
    greeter: { label: 'Greeter Config', shape: 'text', scope: 'zone', group: 'Zone: Systems',
      help: 'Greeter NPC gate config for this zone (jobboard plugin).' },
    work_venue: { label: 'Work Venue (Steady Work)', shape: 'text', scope: 'zone', group: 'Zone: Systems',
      help: 'Marks this zone as a Steady Work shift venue: { role, wage, employer?, name? }. Players past the XP gate can `clock in` here (work plugin).' },
    mis_ok: { label: 'MIS OK', shape: 'flag', scope: 'zone', group: 'Zone: Systems',
      help: 'Zone-gated NPC consent (see npcs.flags.mis_requires_zone_flag).' },

    curtain: { label: 'The Curtain (perimeter wall)', shape: 'flag', scope: 'zone', group: 'Zone: Perimeter',
      help: 'This tile borders the Architect\'s energy wall along the city\'s land edge. Renders a shimmer-edge on the minimap and a curtain line in the room description; the tile stays sealed (no exit crosses it) except at a perimeter_gate. Owner: perimeter (wildlands).' },
    perimeter_gate: { label: 'Perimeter Gate', shape: 'flag', scope: 'zone', group: 'Zone: Perimeter',
      help: 'The one break in the Curtain — the guarded road out to the wilds. Draws a gate glyph on the minimap and carries the exit through the wall. Owner: perimeter (wildlands).' },
    glacis: { label: 'Glacis (kill-zone)', shape: 'flag', scope: 'zone', group: 'Zone: Perimeter',
      help: 'Outward-facing turret killing-ground just beyond a perimeter_gate — the cleared no-man\'s-land the wall guns sweep. Owner: perimeter (wildlands).' },
    gate_warning: { label: 'Gate Warning', shape: 'text', scope: 'zone', group: 'Zone: Perimeter',
      help: 'One-time spoken briefing the gate guards deliver the first time a player steps onto this perimeter tile — what leaving the city costs and which regions lie past the Curtain. The prose lives here; the gatewarn plugin owns only the once-gating + delivery. Owner: gatewarn.' },
    light_beacon: { label: 'Light Beacon', shape: 'flag', scope: 'zone', group: 'Zone: Perimeter',
      help: 'This tile glows bright enough to flood itself and every same-level tile one grid-step away (the 8 surrounding cells) to full brightness, overriding night, power, and weather. Set on the source tile only; the environment sim expands the spill. Owner: environment (getZoneVisibility).' },

    airfield_id: { label: 'Airfield ID', shape: 'text', scope: 'zone', group: 'Zone: Flight',
      help: 'Which airfield this zone belongs to.' },
    airfield_name: { label: 'Airfield Name', shape: 'text', scope: 'zone', group: 'Zone: Flight',
      help: 'Display name of the airfield.' },
    airfield_charter: { label: 'Airfield: Charter', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'An NPC charter pilot flies you somewhere. Needs a charter_pilot NPC assigned to this field. Independent of the rental desk.' },
    airfield_rental: { label: 'Airfield: Rental', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'Self-fly rental desk — `rent` an airframe you pilot yourself. Independent of Charter: a field can offer an NPC ride without renting anything out (Buzzard Field), or vice versa.' },
    charter_vtol_only: { label: 'Charter: VTOL-only', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'Charter pad flies the VTOL Dragonfly off-airfield only — no Mule, no self-fly rental desk (e.g. the Echelon helipad).' },
    airfield_vtol_only: { label: 'Airfield: VTOL-only (helipad)', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'A helipad — no runway, so only VTOL/rotorcraft can be bought, rented, or chartered here (fixed-wings are hidden from every roster).' },
    airfield_dealer: { label: 'Airfield: Dealer', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'Aircraft dealer here.' },
    airfield_fuel: { label: 'Airfield: Fuel', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'Fuel vendor here.' },
    airfield_fuels: { label: 'Airfield: Fuel Types', shape: 'list', scope: 'zone', group: 'Zone: Flight',
      help: 'Fuel types sold, e.g. ["avgas","biofuel"].' },
    airfield_lawless: { label: 'Airfield: Lawless', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'Airfield outside city law.' },
    airfield_theme: { label: 'Airfield: Theme', shape: 'text', scope: 'zone', group: 'Zone: Flight',
      help: 'Overrides the airport backdrop painted out the canopy (city, docks, yards, slag, wastes, default). Inferred from the zone id when unset.' },
    airfield_surface: { label: 'Airfield: Surface', shape: 'text', scope: 'zone', group: 'Zone: Flight',
      help: 'Runway surface flavour for a rough strip, e.g. "dust" for a packed-dirt frontier field.' },
    airspace_restricted: { label: 'Airspace Restricted', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'AA-gated airspace over this zone.' },
    hangar_interior: { label: 'Hangar Interior', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'Inside a hangar.' },
    hangar_interior_zone: { label: 'Hangar Interior Zone', shape: 'text', scope: 'zone', group: 'Zone: Flight',
      help: 'Link from ramp to hangar interior zone id.' },
    hangar_ramp: { label: 'Hangar Ramp', shape: 'text', scope: 'zone', group: 'Zone: Flight',
      help: 'Hangar ramp (aircraft parking) — holds the paired dock zone id.' },
    insurance_desk: { label: 'Insurance Desk', shape: 'flag', scope: 'zone', group: 'Zone: Flight',
      help: 'Aircraft insurance vendor here.' },
    runway: { label: 'Runway', shape: 'enum', options: ['ns', 'ew', 'pad'], scope: 'zone', group: 'Zone: Flight',
      help: 'Marks a runway tile: "ns"/"ew" is the centreline orientation the flight sim aligns its drawn runway to; "pad" is the surrounding asphalt. Stamped by the zone planner on runway tiles.' },
  };

  global.TAG_CATALOG = TAG_CATALOG;
})(typeof window !== 'undefined' ? window : globalThis);

// NOTE: applicability helpers (tagTargets / tagAppliesTo) live in the sibling
// tagHelpers.js, NOT here — this file is regenerated verbatim from JSON whenever
// the Tags screen saves the catalog (see apiPutTagCatalog), which would wipe any
// functions defined here.
